services:
  - type: web
    name: inboxpilot-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
    
  - type: pserv
    name: inboxpilot-db
    env: docker
    region: oregon
    plan: free
    ipAllowList: []
